In [3]:
import hats

trilegal_hats = hats.read_hats("/astro/store/epyc3/data3/hats/catalogs/TRILEGAL_cluster_v08/")
trilegal_hats

In [4]:
trilegal_hats.has_healpix_column()

True

In [5]:
trilegal_hats.catalog_info.explicit_dict()

{'catalog_name': 'TRILEGAL_cluster_v08',
 'catalog_type': 'object',
 'total_rows': 11433322690,
 'ra_column': 'ra',
 'dec_column': 'dec',
 'healpix_column': '_healpix_29',
 'healpix_order': 29,
 'npix_suffix': '.parquet',
 'skymap_order': 10,
 'hats_max_rows': 10000000,
 'moc_sky_fraction': 0.74467}

In [63]:
trilegal_hats.get_healpix_pixels()[19]

Order: 2, Pixel: 70

In [2]:
import pyarrow.parquet as pq

pq.read_metadata("/astro/store/epyc3/data3/hats/catalogs/TRILEGAL_cluster_v08/dataset/_common_metadata").schema.to_arrow_schema()
# pq.read_metadata("/astro/store/epyc3/data3/hats/catalogs/TRILEGAL_cluster_v08/dataset/Norder=4/Dir=0/Npix=3071.parquet").schema.to_arrow_schema()

ra: double
dec: double
glon: double
glat: double
m_ini: float
logage: float
FeH: float
DM: float
Av: float
mratio: float
mass: float
logl: float
logte: float
logg: float
umag: float
gmag: float
rmag: float
imag: float
zmag: float
ymag: float
ring256: int32
comp: int16
label: int16
Ar: float
Mr: float
ug: float
gr: float
ri: float
iz: float
gi: float
_healpix_29: int64

In [61]:
import nested_pandas as npd

npd.read_parquet("/astro/store/epyc3/data3/hats/catalogs/TRILEGAL_cluster_v08/dataset/Norder=3/Dir=0/Npix=767.parquet", use_pandas_metadata=False)

,ra,dec,glon,glat,m_ini,logage,FeH,DM,Av,mratio,mass,logl,logte,logg,umag,gmag,rmag,imag,zmag,ymag,ring256,comp,label,Ar,Mr,ug,gr,ri,iz,gi,Norder,Dir,Npix
_healpix_29,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
3454260916081733704,315.002683,-9.589089,39.149389,-32.877798,0.24078,10.07,-2.19,12.0,0.261,0.0,0.239,-1.772,3.6328,5.071,24.731001,22.700001,21.677,21.212999,20.969,20.837,458112,3,1,0.231532,9.445467,1.936072,0.930388,0.408201,0.198156,1.338589,<NA>,<NA>,<NA>
3454260917235596163,314.99857,-9.588133,39.148278,-32.873737,0.33292,10.11,-1.94,16.299999,0.43,0.0,0.332,-1.527,3.6392,4.995,28.360001,26.346001,25.347,24.9,24.667,24.539,458112,3,1,0.381452,8.665548,1.857605,0.84642,0.355071,0.157472,1.201491,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3458764512547433332,314.99804,-0.003887,48.913354,-28.260211,0.32182,10.05,-0.66,13.05,0.244,0.0,0.32,-1.824,3.5562,4.944,27.643999,24.802999,23.364,22.525999,22.099001,21.893999,394624,2,1,0.216452,10.097548,2.752254,1.352419,0.785836,0.384141,2.138255,<NA>,<NA>,<NA>
3458764513145416780,315.002045,-0.002003,48.917538,-28.262661,0.18279,9.87,-0.23,11.25,0.28,0.0,0.182,-2.465,3.4881,5.067,29.165001,25.860001,24.368999,22.771999,22.028999,21.674,394624,1,1,0.248387,12.870613,3.203162,1.391646,1.537139,0.693819,2.928785,<NA>,<NA>,<NA>

In [6]:
import lsdb

trilegal_lsdb = lsdb.open_catalog("/astro/store/epyc3/data3/hats/catalogs/TRILEGAL_cluster_v08/")
trilegal_lsdb

Dask NestedFrame Structure:
                                  ra              dec             glon             glat           m_ini          logage             FeH              DM              Av          mratio            mass            logl           logte            logg            umag            gmag            rmag            imag            zmag            ymag         ring256            comp           label              Ar              Mr              ug              gr              ri              iz              gi
npartitions=2520
0                    double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  float[pyarrow]  float[pyarrow]  float[pyarrow]  float[pyarrow]  float[pyarrow]  float[pyarrow]  float[pyarrow]  float[pyarrow]  float[pyarrow]  float[pyarrow]  float[pyarrow]  float[pyarrow]  float[pyarrow]  float[pyarrow]  float[pyarrow]  float[pyarrow]  int32[pyarrow]  int16[pyarrow]  int16[pyarrow]  float[pyarrow]  float[pyarrow]  float[pyarrow]  float[pyarrow]  float[pyarrow]  float[pyarrow]  float[pyarrow]
18014398509481984                ...              ...              ...              ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...
...                              ...              ...              ...              ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...
3454260914193170432              ...              ...              ...              ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...
3458764513820540928              ...              ...              ...              ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...             ...
Dask Name: nestedframe, 3 expressions
Expr=MapPartitions(NestedFrame)

In [7]:
len(trilegal_lsdb.get_healpix_pixels())

2520

In [8]:
trilegal_lsdb.hc_structure.has_healpix_column()

True

In [9]:
trilegal_cat = trilegal_lsdb.box_search(ra=(3, 5), dec=(3, 5), fine=False)

In [30]:
import nested_pandas

nested_pandas.__version__

'0.6.8'